# Generated by Django 4.2.11 on 2026-06-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDADocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('signed_date', models.DateField()),
                ('signature', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='ndas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ndadocument', to='employees.employee')),
            ],
        ),
    ]
