# Generated by Django 4.2.11 on 2026-06-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndadocument',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
