# Generated by Django 4.2.11 on 2026-06-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=200)),
                ('previous_experience', models.TextField(blank=True)),
                ('pan_number', models.CharField(max_length=10)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('photograph', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('aadhaar_copy', models.FileField(blank=True, null=True, upload_to='aadhaar/')),
                ('pan_copy', models.FileField(blank=True, null=True, upload_to='pan/')),
                ('educational_certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeedetails', to='employees.employee')),
            ],
        ),
    ]
