# Generated by Django 4.2.11 on 2026-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='previous_experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
