# Generated by Django 4.2.11 on 2026-06-19 08:37

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_employeedetails_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='aadhaar_copy',
            field=models.FileField(blank=True, null=True, upload_to=apps.documents.models.EmployeeUploadPath('aadhaar')),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='educational_certificates',
            field=models.FileField(blank=True, null=True, upload_to=apps.documents.models.EmployeeUploadPath('certificates')),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='pan_copy',
            field=models.FileField(blank=True, null=True, upload_to=apps.documents.models.EmployeeUploadPath('pan')),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='photograph',
            field=models.FileField(blank=True, null=True, upload_to=apps.documents.models.EmployeeUploadPath('photograph')),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=apps.documents.models.EmployeeUploadPath('resume')),
        ),
    ]
